### ISSUE TITLE
Dynamism Gems are not random

### ISSUE THREAD

**Issue by 04Slash** [Tiyth/Minecraft-Guides-Astral-Sorcery#10]
Page in question: https://minecraftguides.net/AS/attunement/dynamism-gems

On the Dynamism gem page for Astral Sorcery the page states that the outcome of the Dynamism gems are random. In 1.12.2 this is not true however. I did some testing and found that the gem outcome is related to the time that the final stage of the gem is formed at. It should be noted this test was conducted in the 'FTB Interactions' modpack. I don't see any config options to change this behavior. The gems are also labeled as 'Sky', 'Day', and 'Night' [in the code](https://github.com/HellFirePvP/AstralSorcery/blob/master/src/main/java/hellfirepvp/astralsorcery/common/item/gem/GemType.java).

For a little more info on the tests I conducted:
- All tests were done with random tick speed of 1000 (unsure if this even effects the growth. I don't think it does tbh) and spammed with a time in a bottle to speed up crystal growth. I am unsure if this would make a difference at all but I figured I'd mention in case it does.
- I placed 64 rock crystals and threw in glowstone. I kept the time at 18000 (moon directly above) and 32/32 of the gems that formed turned out to be Fengarum Gems. The other 32 didn't form, and I decided this was enough proof, for now.
- I did the same test as above, but this time at 6000 (sun directly above). 31/31 of the gems that formed turned out as Ilium gems. In this time, there were ~10 additional crystals that formed from the first bunch that all turned into Ilium gems.
- Same test as above, but I choose 23000 (sunrise). Because of how consistent the other results were, I was satisfied when 17/17 gems turned out to be Ourium gems. In this time, 20 other gems from previous tests turned out to be Ourium gems.

To figure out the exact times I played around with `/time set #` and `/gamerule doDaylightCycle false`
- Fengarums will trigger between 14743-21257
- Iliums will trigger between 23658-12342
- Ourium will trigger between 12343-14742 and 21258-23657

I decided to make an instance with just Astral + Random Things (for time in a bottle) to ensure that there is nothing changing the mod's behavior, as well as to check if 100% of the outcomes will match the above times with a sample size of 16. Out of the 3 times I choose (14742, 14743, and 12342) all 3 of them gave 16/16 of the respective gems.

On another note, it would appear that once gems are grown, there is a change they will revert back 1 stage. I don't know if this is a bug with the mod or using time in a bottle, or if there's just a random chance for it to revert back.

**Comment by Tiyth** [comment]
Wow thank you, I have added this to the guide.

**Comment by 04Slash** [comment]
Mind making just one more tweak?

> Growing these crystals takes time and the gem outcome is related to the time that the final stage of the gem is formed at, these gems are no different from each other, the stats are always random.

Add: If you don't like the outcome of them gem it's possible to wait. After some time it will convert back into the previous stage which will allow it to grow into a new Dynasty gem, depending on the time. This is useful if you don't have spare rock crystals to grow a new gem.

Thanks for these guides btw. I find them very useful.

**Comment by Tiyth** [comment]
Added, thank you!
