### ISSUE TITLE
Resplendent Prism Slot Change

### ISSUE THREAD

**Issue by Gekocaretaker** [Tiyth/Minecraft-Guides-Astral-Sorcery#11]
The Resplendent Prism uses Curios instead of Baubles in 1.15.2 and up. In 1.12.2 was the last version to use baubles. I think that the guide should be updated to support both versions.
Curios uses necklaces instead of amulets.

**Comment by Gekocaretaker** [comment]
Also, some other things should be added:
In 1.15.2, instead of getting a new altar, your old one gets upgraded.
In 1.15.2, you need to reveal the collector crystal to starlight, and that will turn the crafting table into a luminous crafting table.
There is a few other minor changes to do with some structures and other minor things.

**Comment by Tiyth** [comment]
Thanks, I have added these changes apart from the altar getting upgraded rather than crafting a new one, ill look into this and see how it works so I can change things accordingly.
