### ISSUE TITLE
Pages with spaces in the name are causing redirect loops

### ISSUE THREAD

**Issue by amezick** [Tiyth/Minecraft-Guides-Astral-Sorcery#9]
https://minecraftguides.net/AS/getting%20started

Looking at the browser dev tools, it looks like the server redirects "foo%20bar" to "foo bar" and then the browser does it's "browser thing" and requests "foo%20bar" again.
The other two guides use '-' instead of spaces in the links.

**Comment by Tiyth** [comment]
Thank you! Fixing this now!

**Comment by Tiyth** [comment]
This has been fixed
